### PR TITLE
`ParameterFormatter` rewrite with improved escape handling

### LINKED ISSUE #1626: Specific message pattern causes ArrayIndexOutOfBoundsException throwed by ParameterizedMessage.init()
## Description

Message pattern `"\\\\{}"` causes `ArrayIndexOutOfBoundsException` during ParameterizedMessage.init()

## Configuration

Default spring boot configuration.

**Version:** [Log4j version]

Known reproducable versions: 2.12.0 - 2.20.0

**Operating system:** [OS and version]

Windows 10

**JDK:** [JDK distribution and version]

Oracle JDK 1.8u362

## Logs

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at org.apache.logging.log4j.message.ParameterFormatter.countArgumentPlaceholders2(ParameterFormatter.java:121)
	at org.apache.logging.log4j.message.ParameterizedMessage.init(ParameterizedMessage.java:149)
	at org.apache.logging.log4j.message.ParameterizedMessage.<init>(ParameterizedMessage.java:123)
	at org.apache.logging.log4j.message.ParameterizedMessage.<init>(ParameterizedMessage.java:132)
	at org.apache.logging.log4j.message.ParameterizedMessageFactory.newMessage(ParameterizedMessageFactory.java:70)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2033)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899)
	at org.apache.logging.slf4j.Log4jLogger.error(Log4jLogger.java:304)
        ......
```

## Reproduction

```java
package org.apache.logging.log4j.message;

public class Test {
    private static final String testMsg1 = "\\\\{}";
    private static final String testMsg2 = "\\\\{} blabla";
    private static final String[] testArgs = {"a"};

    public static void main(String[] args) {
        System.out.println(formatUsingReusableParameterizedMessage(testMsg2));  // \a blabla
        System.out.println(formatUsingParameterizedMessage(testMsg2));          // \a blabla
        System.out.println(formatUsingReusableParameterizedMessage(testMsg1));  // \a
        System.out.println(formatUsingParameterizedMessage(testMsg1));          // throws ArrayIndexOutOfBoundsException
    }

    public static String formatUsingParameterizedMessage(final String msg) {
        return new ParameterizedMessage(msg, testArgs).getFormattedMessage();
    }

    public static String formatUsingReusableParameterizedMessage(final String msg) {
        return new ReusableParameterizedMessage().set(msg, testArgs).getFormattedMessage();
    }
}
```

### PR DESCRIPTION
**Pull request by vy**
Fixes  #1626.

### CODE REVIEW

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java [hunk 1]
```diff
@@ -17,156 +17,167 @@
...
+import org.junit.jupiter.params.provider.CsvSource;
+import org.junit.jupiter.params.provider.MethodSource;
 
-import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.assertj.core.api.Assertions.assertThat;
 
 /**
  * Tests {@link ParameterFormatter}.
  */
 public class ParameterFormatterTest {
```
Comment (rgoers) [inline log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:35]: How do I know you didn't change behavior when you have modified the tests?

File: log4j-perf/src/main/java/org/apache/logging/log4j/message/ParameterFormatterBenchmark.java [hunk 2]
```diff
@@ -51,135 +46,83 @@ public static class ThreadState {
         char[] copy = new char[4096];
     }
```
Comment (rgoers) [inline log4j-perf/src/main/java/org/apache/logging/log4j/message/ParameterFormatterBenchmark.java:48]: Why are all these methods deleted?

File: log4j-perf/src/main/java/org/apache/logging/log4j/message/ParameterFormatterBenchmark.java [hunk 3]
```diff
@@ -51,135 +46,83 @@ public static class ThreadState {
...
-    @Benchmark
-    @BenchmarkMode(Mode.SampleTime)
-    @OutputTimeUnit(TimeUnit.NANOSECONDS)
-    public int latency9Params(final ThreadState state) {
-        state.buffer.setLength(0);
-        final int count = ParameterFormatter.countArgumentPlaceholders("p1={}, p2={}, p3={}, p4={}, p5={}, p6={}, p7={}, p8={}, p9={}");
-        ParameterFormatter.formatMessage(state.buffer, "p1={}, p2={}, p3={}, p4={}, p5={}, p6={}, p7={}, p8={}, p9={}", ARGS, count);
-        return state.buffer.length();
-    }
+//    @Benchmark
```
Comment (rgoers) [inline log4j-perf/src/main/java/org/apache/logging/log4j/message/ParameterFormatterBenchmark.java:49]: Why are these benchmarks commented out?

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java (hunk 1 above)
Comment (vy) [reply log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:35]: I copied them intact into a `@ParametrizedTest`s. I will create a thread for the ones I either changed or added.

File: log4j-perf/src/main/java/org/apache/logging/log4j/message/ParameterFormatterBenchmark.java (hunk 3 above)
Comment (vy) [reply log4j-perf/src/main/java/org/apache/logging/log4j/message/ParameterFormatterBenchmark.java:49]: As I have indicated both in the email and PR description, I am working on the benchmarks as we speak.

File: log4j-perf/src/main/java/org/apache/logging/log4j/message/ParameterFormatterBenchmark.java (hunk 2 above)
Comment (vy) [reply log4j-perf/src/main/java/org/apache/logging/log4j/message/ParameterFormatterBenchmark.java:48]: Because they are package-private and not used anymore.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java [hunk 4]
```diff
@@ -17,156 +17,167 @@
...
-        assertEquals("Test message \\ab c", result);
+    @ParameterizedTest
+    @CsvSource({
+            "0,,false,",
+            "0,,false,aaa",
+            "0,,true,\\{}",
+            "1,0,false,{}",
+            "1,0,true,{}\\{}",
+            "1,2,true,\\\\{}",
+            "2,8:10,true,foo \\{} {}{}",
```
Comment (vy) [inline log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:44]: @rgoers, these two scenarios are new.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java [hunk 5]
```diff
@@ -17,156 +17,167 @@
...
+                        "Test message {}{} {}\\",
+                        new Object[]{"a", "b", "c"},
+                        3,
+                        "Test message ab c\\"
+                },
+                new Object[]{
+                        "Test message {}{} {}\\\\",
+                        new Object[]{"a", "b", "c"},
+                        3,
+                        "Test message ab c\\"
```
Comment (vy) [inline log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:118]: @rgoers, behaviour change: previously this was returning `Test message ab c\\\\`. I think this was a bug in the earlier version, since in other occasions `\\\\\` gets formatted to `\\`; for instance, see the next test scenario. Hence, this behaviour should be consistent, IMO and that is what I strived to capture in the new version.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java [hunk 6]
```diff
@@ -17,156 +17,167 @@
...
```
Comment (vy) [inline log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:160]: @rgoers, similar to the above, this was returning `Test message ab c\\\\` earlier.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java [hunk 7]
```diff
@@ -17,156 +17,167 @@
...
+                        "Test message \\\\{}{} {}",
+                        new Object[]{"a", "b", "c"},
+                        3,
+                        "Test message \\ab c"
+                },
+                new Object[]{
+                        "foo \\\\\\{} {}",
+                        new Object[]{"bar"},
+                        1,
+                        "foo \\{} bar"
```
Comment (vy) [inline log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:172]: @rgoers, this scenario is new and is causing the old version to throw exception.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java [hunk 8]
```diff
@@ -17,156 +17,167 @@
...
+                },
+                new Object[]{
+                        "missing arg {} {}",
+                        new Object[]{1, 2},
+                        1,
+                        "missing arg 1 {}"
```
Comment (vy) [inline log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:178]: @rgoers, this is new too.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterizedMessageTest.java [hunk 9]
```diff
@@ -115,7 +115,7 @@ public void testFormatStringArgsWithTrailingEscapedEscape() {
         final String testMsg = "Test message {}{} {}\\\\";
         final String[] args = { "a", "b", "c" };
         final String result = ParameterizedMessage.format(testMsg, args);
-        assertEquals("Test message ab c\\\\", result);
+        assertEquals("Test message ab c\\", result);
```
Comment (vy) [inline log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterizedMessageTest.java:118]: @rgoers, this is changed due to the same reason I have elaborated on in `ParameterFormatterTest` comments.

**Comment by vy** [comment]
@rgoers, I have benchmarked the new implementation (prefixed with `Vy` in the results) against the old ones using Java 17.0.8 (Zulu) on my GNU/Linux system:

```
Benchmark                                        Mode      Cnt       Score   Error  Units
latency3Params                                 sample  1433326     177.957 ± 3.014  ns/op
latency3Params:latency3Params·p0.00            sample              131.000          ns/op
latency3Params:latency3Params·p0.50            sample              149.000          ns/op
latency3Params:latency3Params·p0.90            sample              189.000          ns/op
latency3Params:latency3Params·p0.95            sample              231.000          ns/op
latency3Params:latency3Params·p0.99            sample              299.000          ns/op
latency3Params:latency3Params·p0.999           sample             4762.768          ns/op
latency3Params:latency3Params·p0.9999          sample            29344.000          ns/op
latency3Params:latency3Params·p1.00            sample           458752.000          ns/op

latency3ParamsV2                               sample  1097078     141.178 ± 4.841  ns/op
latency3ParamsV2:latency3ParamsV2·p0.00        sample               92.000          ns/op
latency3ParamsV2:latency3ParamsV2·p0.50        sample              111.000          ns/op
latency3ParamsV2:latency3ParamsV2·p0.90        sample              126.000          ns/op
latency3ParamsV2:latency3ParamsV2·p0.95        sample              194.000          ns/op
latency3ParamsV2:latency3ParamsV2·p0.99        sample              234.000          ns/op
latency3ParamsV2:latency3ParamsV2·p0.999       sample             4510.736          ns/op
latency3ParamsV2:latency3ParamsV2·p0.9999      sample            29376.000          ns/op
latency3ParamsV2:latency3ParamsV2·p1.00        sample           387072.000          ns/op

latency3ParamsVy                               sample  1078265     138.288 ± 2.333  ns/op
latency3ParamsVy:latency3ParamsVy·p0.00        sample               92.000          ns/op
latency3ParamsVy:latency3ParamsVy·p0.50        sample              111.000          ns/op
latency3ParamsVy:latency3ParamsVy·p0.90        sample              119.000          ns/op
latency3ParamsVy:latency3ParamsVy·p0.95        sample              195.000          ns/op
latency3ParamsVy:latency3ParamsVy·p0.99        sample              222.000          ns/op
latency3ParamsVy:latency3ParamsVy·p0.999       sample             8124.848          ns/op
latency3ParamsVy:latency3ParamsVy·p0.9999      sample            29957.549          ns/op
latency3ParamsVy:latency3ParamsVy·p1.00        sample           280576.000          ns/op

=========================================================================================

latency5Params                                 sample  1725194     277.162 ± 2.627  ns/op
latency5Params:latency5Params·p0.00            sample              216.000          ns/op
latency5Params:latency5Params·p0.50            sample              237.000          ns/op
latency5Params:latency5Params·p0.90            sample              300.000          ns/op
latency5Params:latency5Params·p0.95            sample              342.000          ns/op
latency5Params:latency5Params·p0.99            sample              472.000          ns/op
latency5Params:latency5Params·p0.999           sample             9228.880          ns/op
latency5Params:latency5Params·p0.9999          sample            30063.376          ns/op
latency5Params:latency5Params·p1.00            sample           302080.000          ns/op

latency5ParamsV2                               sample  1418889     186.454 ± 1.915  ns/op
latency5ParamsV2:latency5ParamsV2·p0.00        sample              134.000          ns/op
latency5ParamsV2:latency5ParamsV2·p0.50        sample              155.000          ns/op
latency5ParamsV2:latency5ParamsV2·p0.90        sample              200.000          ns/op
latency5ParamsV2:latency5ParamsV2·p0.95        sample              281.000          ns/op
latency5ParamsV2:latency5ParamsV2·p0.99        sample              314.000          ns/op
latency5ParamsV2:latency5ParamsV2·p0.999       sample             7617.760          ns/op
latency5ParamsV2:latency5ParamsV2·p0.9999      sample            29603.552          ns/op
latency5ParamsV2:latency5ParamsV2·p1.00        sample           110720.000          ns/op

latency5ParamsVy                               sample  1404473     186.567 ± 1.949  ns/op
latency5ParamsVy:latency5ParamsVy·p0.00        sample              136.000          ns/op
latency5ParamsVy:latency5ParamsVy·p0.50        sample              155.000          ns/op
latency5ParamsVy:latency5ParamsVy·p0.90        sample              167.000          ns/op
latency5ParamsVy:latency5ParamsVy·p0.95        sample              286.000          ns/op
latency5ParamsVy:latency5ParamsVy·p0.99        sample              309.000          ns/op
latency5ParamsVy:latency5ParamsVy·p0.999       sample             9672.416          ns/op
latency5ParamsVy:latency5ParamsVy·p0.9999      sample            30272.000          ns/op
latency5ParamsVy:latency5ParamsVy·p1.00        sample            40768.000          ns/op

=========================================================================================

latency7Params                                 sample  1225848     369.877 ± 2.744  ns/op
latency7Params:latency7Params·p0.00            sample              297.000          ns/op
latency7Params:latency7Params·p0.50            sample              315.000          ns/op
latency7Params:latency7Params·p0.90            sample              392.000          ns/op
latency7Params:latency7Params·p0.95            sample              443.000          ns/op
latency7Params:latency7Params·p0.99            sample              645.000          ns/op
latency7Params:latency7Params·p0.999           sample            18112.000          ns/op
latency7Params:latency7Params·p0.9999          sample            31264.000          ns/op
latency7Params:latency7Params·p1.00            sample           280576.000          ns/op

latency7ParamsV2                               sample  1944254     246.963 ± 1.646  ns/op
latency7ParamsV2:latency7ParamsV2·p0.00        sample              184.000          ns/op
latency7ParamsV2:latency7ParamsV2·p0.50        sample              209.000          ns/op
latency7ParamsV2:latency7ParamsV2·p0.90        sample              275.000          ns/op
latency7ParamsV2:latency7ParamsV2·p0.95        sample              373.000          ns/op
latency7ParamsV2:latency7ParamsV2·p0.99        sample              421.000          ns/op
latency7ParamsV2:latency7ParamsV2·p0.999       sample             7347.920          ns/op
latency7ParamsV2:latency7ParamsV2·p0.9999      sample            30112.000          ns/op
latency7ParamsV2:latency7ParamsV2·p1.00        sample            95616.000          ns/op

latency7ParamsVy                               sample  1770285     235.908 ± 2.137  ns/op
latency7ParamsVy:latency7ParamsVy·p0.00        sample              186.000          ns/op
latency7ParamsVy:latency7ParamsVy·p0.50        sample              196.000          ns/op
latency7ParamsVy:latency7ParamsVy·p0.90        sample              244.000          ns/op
latency7ParamsVy:latency7ParamsVy·p0.95        sample              383.000          ns/op
latency7ParamsVy:latency7ParamsVy·p0.99        sample              412.000          ns/op
latency7ParamsVy:latency7ParamsVy·p0.999       sample             6123.424          ns/op
latency7ParamsVy:latency7ParamsVy·p0.9999      sample            29792.000          ns/op
latency7ParamsVy:latency7ParamsVy·p1.00        sample           441344.000          ns/op

=========================================================================================

latency9Params                                 sample  1847760     466.266 ± 2.067  ns/op
latency9Params:latency9Params·p0.00            sample              381.000          ns/op
latency9Params:latency9Params·p0.50            sample              411.000          ns/op
latency9Params:latency9Params·p0.90            sample              504.000          ns/op
latency9Params:latency9Params·p0.95            sample              630.000          ns/op
latency9Params:latency9Params·p0.99            sample              814.000          ns/op
latency9Params:latency9Params·p0.999           sample            16992.000          ns/op
latency9Params:latency9Params·p0.9999          sample            30976.000          ns/op
latency9Params:latency9Params·p1.00            sample           326144.000          ns/op

latency9ParamsV2                               sample  1559018     294.029 ± 2.193  ns/op
latency9ParamsV2:latency9ParamsV2·p0.00        sample              225.000          ns/op
latency9ParamsV2:latency9ParamsV2·p0.50        sample              251.000          ns/op
latency9ParamsV2:latency9ParamsV2·p0.90        sample              351.000          ns/op
latency9ParamsV2:latency9ParamsV2·p0.95        sample              475.000          ns/op
latency9ParamsV2:latency9ParamsV2·p0.99        sample              534.000          ns/op
latency9ParamsV2:latency9ParamsV2·p0.999       sample             6727.848          ns/op
latency9ParamsV2:latency9ParamsV2·p0.9999      sample            28099.139          ns/op
latency9ParamsV2:latency9ParamsV2·p1.00        sample           292864.000          ns/op

latency9ParamsVy                               sample  1549119     299.646 ± 2.214  ns/op
latency9ParamsVy:latency9ParamsVy·p0.00        sample              231.000          ns/op
latency9ParamsVy:latency9ParamsVy·p0.50        sample              252.000          ns/op
latency9ParamsVy:latency9ParamsVy·p0.90        sample              299.000          ns/op
latency9ParamsVy:latency9ParamsVy·p0.95        sample              477.000          ns/op
latency9ParamsVy:latency9ParamsVy·p0.99        sample              544.000          ns/op
latency9ParamsVy:latency9ParamsVy·p0.999       sample            13662.080          ns/op
latency9ParamsVy:latency9ParamsVy·p0.9999      sample            30464.000          ns/op
latency9ParamsVy:latency9ParamsVy·p1.00        sample           329216.000          ns/op
```

Hence, I can confidently say that the new formatter is even faster!

File: log4j-api/src/main/java/org/apache/logging/log4j/message/ReusableParameterizedMessage.java [hunk 10]
```diff
@@ -119,30 +119,28 @@ public Message memento() {
...
-        try {
-            // try the fast path first
-            return ParameterFormatter.countArgumentPlaceholders2(messagePattern, indices);
-        } catch (final Exception ex) { // fallback if more than int[] length (256) parameter placeholders
-            return ParameterFormatter.countArgumentPlaceholders(messagePattern);
-        }
+    private static MessagePatternAnalysis analyzePattern(final String pattern, final MessagePatternAnalysis patternAnalysis) {
+        return (patternAnalysis != null && ParameterFormatter.analyzePattern(pattern, patternAnalysis))
+                ? patternAnalysis
+                : ParameterFormatter.analyzePattern(pattern);
```
Comment (ppkarwasz) [inline log4j-api/src/main/java/org/apache/logging/log4j/message/ReusableParameterizedMessage.java:133]: Nice way to bootstrap the pattern analysis data, but I would make sure that:
 - `placeholderCharIndices` has size 10 at least,
 - if the number of indices exceeds a preconfigured threshold (e.g. 256), the `MessagePatternAnalysis` is dropped by `clear()`.

**Review by ppkarwasz — CHANGES_REQUESTED** [review]
I like the idea of replacing `formatMessage1` through `formatMessage42` with a single logic.

If it limits the allocations mentioned below, it looks good to me.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java (hunk 4 above)
Comment (ppkarwasz) [reply log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:44]: Maybe we could also test `{\\}` as an alternative to `\\{}`.

File: log4j-api/src/main/java/org/apache/logging/log4j/message/ReusableParameterizedMessage.java (hunk 10 above)
Comment (vy) [reply log4j-api/src/main/java/org/apache/logging/log4j/message/ReusableParameterizedMessage.java]: See the changes in a996006f6d1fcccd7bd37c4ec5e308ddaf891fb3, please.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java (hunk 4 above)
Comment (vy) [reply log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:45]: @ppkarwasz, good point. Added in 763bc271b1bd3dbe4bed0361d2bbab6d688abb28.

**Review by ppkarwasz — APPROVED** [review]
LGTM

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java (hunk 5 above)
Comment (vy) [reply log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:120]: It has been two weeks. I am resolving this conversation.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java (hunk 6 above)
Comment (vy) [reply log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:162]: It has been two weeks. I am resolving this conversation.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java (hunk 8 above)
Comment (vy) [reply log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:180]: It has been two weeks. I am resolving this conversation.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterizedMessageTest.java (hunk 9 above)
Comment (vy) [reply log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterizedMessageTest.java:118]: It has been two weeks. I am resolving this conversation.
