### PR TITLE
Fix `ConcurrentModificationException` in `updateLoggers()`

### LINKED ISSUE #3234: ConcurrentModificationException in LoggerContext due to race condition
## Description

Presumably due to https://github.com/apache/logging-log4j2/commit/a1dfa853c96604ded1f253da2ec25f8f2f95ef25 my application throws an error when loggers get changed from multiple threads.
This is likely because `InternalLoggerRegistry#getLoggers` does not return a thread-safe stream.
Streams are by nature evaluated on the fly, thus still using the values of `loggerRefByNameByMessageFactory` after `readLock` was unlocked.
When multiple threads modify `loggerRefByNameByMessageFactory`, sometimes it errors with the attached error.
This happens inconsistently because it's a race condition, but I've been able to get this error a few times.

## Configuration

**Version:** 2.24.2

**Operating system:** Windows

**JDK:** openjdk version "21.0.4" 2024-07-16 LTS

## Logs

```
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1792) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.WeakHashMap$ValueSpliterator.forEachRemaining(WeakHashMap.java:1223) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.apache.logging.log4j.core.LoggerContext.updateLoggers(LoggerContext.java:776) ~[?:?]
	at org.apache.logging.log4j.core.LoggerContext.updateLoggers(LoggerContext.java:766) ~[?:?]
	at org.apache.logging.log4j.core.config.Configurator.setLevel(Configurator.java:379) ~[?:?]
	at org.apache.logging.log4j.core.config.Configurator.setLevel(Configurator.java:414) ~[?:?]
	at com.soulfiremc.server.SoulFireServer.setupLogging(SoulFireServer.java:213) ~[?:?]
	at com.soulfiremc.server.SoulFireServer.setupLoggingAndVia(SoulFireServer.java:208) ~[?:?]
	at com.soulfiremc.server.InstanceManager.start(InstanceManager.java:194) ~[?:?]
	at com.soulfiremc.server.SoulFireScheduler.lambda$wrapFuture$6(SoulFireScheduler.java:140) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at com.soulfiremc.server.SoulFireScheduler.runCommand(SoulFireScheduler.java:154) ~[?:?]
	at com.soulfiremc.server.SoulFireScheduler.lambda$schedule$2(SoulFireScheduler.java:79) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```

This shows the stream being collected due to the forEach call in `LoggerContext#updateLoggers`, but there being no read lock, therefore causing this race condition.

## Reproduction

I unfortunately cannot provide an example because I do not have much experience with reproducing race conditions.

### PR DESCRIPTION
**Pull request by ppkarwasz**
The `InternalLoggerRegistry` implementation introduced in version `2.24.2` did not return a copy of the registry, when `InternalLoggerRegistry.getLoggers()` was called. This could lead to a `ConcurrentModificationException` if a thread creates a new logger, while another thread calls `LoggerContext.updateLoggers()`.

Closes #3234

### CODE REVIEW

**Review by vy — APPROVED** [review]

**Comment by garydgregory** [comment]
Hi all,

Does this mean a 2.24.3 is around the corner?

**Comment by ppkarwasz** [comment]
> Does this mean a 2.24.3 is around the corner?

@garydgregory, I would wait a couple of weeks to see if other bugs are reported, but, yes, I think we should release a `2.24.3`.

We can also release `2.25.0`, but that will bring other problems and I have some long term plans for `2.24.x`.

File: log4j-core/src/main/java/org/apache/logging/log4j/core/LoggerContext.java [hunk 1]
```diff
@@ -513,7 +512,7 @@ public Logger getLogger(final String name) {
      * @return a collection of the current loggers.
      */
     public Collection<Logger> getLoggers() {
-        return loggerRegistry.getLoggers().collect(Collectors.toList());
+        return loggerRegistry.getLoggers();
```
Comment (vy) [inline log4j-core/src/main/java/org/apache/logging/log4j/core/LoggerContext.java:515]: Shouldn't we rather keep the old defensive copy around to avoid similar problems from integrators?

Comment (ppkarwasz) [reply log4j-core/src/main/java/org/apache/logging/log4j/core/LoggerContext.java:515]: `Collectors.toList()` does make a copy, right?

I could add a test for that in case the implementation of `InternalLoggerRegistry.getLoggers()` changes

Comment (vy) [reply log4j-core/src/main/java/org/apache/logging/log4j/core/LoggerContext.java:515]: I'm not concerned about `ILR`, I think it is covered, but integrators providing their own `LR` and such. Anyway... Checked the code and this line used to be `return loggerRegistry.getLoggers()`. :+1:

**Comment by ppkarwasz** [comment]
@tnleeuw,

I removed the usage of `forEach()` in https://github.com/apache/logging-log4j2/pull/3235/commits/4fa2d548c9f704db37e3a6f0a50e06e3d2958d8a. Could you review the changes?

**Comment by tnleeuw** [comment]
> @tnleeuw,
> 
> I removed the usage of `forEach()` in [4fa2d54](https://github.com/apache/logging-log4j2/commit/4fa2d548c9f704db37e3a6f0a50e06e3d2958d8a). Could you review the changes?

Looks good to me!

**Comment by kelunik** [comment]
> @garydgregory, I would wait a couple of weeks to see if other bugs are reported, but, yes, I think we should release a 2.24.3.

Why? Can't you just release 2.24.4 if another bug is found?

**Comment by ppkarwasz** [comment]
> > @garydgregory, I would wait a couple of weeks to see if other bugs are reported, but, yes, I think we should release a 2.24.3.
> 
> Why? Can't you just release 2.24.4 if another bug is found?

An Apache release process requires at least three maintainers and has a 72 hours voting period. Unless the reported problem affects most users, my personal policy is to wait a week or two to give users the time to report other problems.

I will start the release process for `2.24.3` tomorrow, which will contain a fix to this bug and the one reported in #3252 (a strange interaction between Spring Boot, ActiveMQ and Log4j API).

**Comment by kelunik** [comment]
Thanks for providing these details!
