### PR TITLE
Mark `JdkMapAdapterStringMap` as frozen if map is immutable

### LINKED ISSUE #2098: Using `Map.of` in a `ContextDataProvider` implementation throws UOE
## Description

I'm using logj2 with a custom `ContextDataProvider`, and then using the [aws lambda appender](https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html#java-logging-log4j2). My `ContextDataProvider` implementation uses `Map.of` methods from JDK to create cheap immutable maps, but apparently that doesn't work and throws UOE.

In the stacktrace it's shown that a method down the stack invokes `ImmutableCollections.AbstractImmutableMap::clear`, which throws UOE. Interesting enough, in many online examples they use `Collections.emptyMap()` for the empty map, which doesn't throw UOE on `clear`.

What puzzles me though is that I wasn't able to reproduce this issue with the log4j2-core console appender. Is the amazon appender doing something strange, or is this a bug of log4j2-core?

## Configuration

**Version:** 2.22.0

**Operating system:** Linux

**JDK:** 21 (amazon)

## Logs

```
2023-12-15T11:26:15.337000+00:00  WARN StatusConsoleListener org.apache.logging.log4j.spi.AbstractLogger caught java.lang.UnsupportedOperationException logging ReusableSimpleMessage: Incremented counter!
2023-12-15T11:26:15.338000+00:00  java.lang.UnsupportedOperationException
2023-12-15T11:26:15.338000+00:00  at java.base/java.util.ImmutableCollections.uoe(Unknown Source)
2023-12-15T11:26:15.338000+00:00  at java.base/java.util.ImmutableCollections$AbstractImmutableMap.clear(Unknown Source)
2023-12-15T11:26:15.338000+00:00  at org.apache.logging.log4j.core.impl.JdkMapAdapterStringMap.clear(JdkMapAdapterStringMap.java:122)
2023-12-15T11:26:15.338000+00:00  at org.apache.logging.log4j.core.impl.MutableLogEvent.clear(MutableLogEvent.java:143)
2023-12-15T11:26:15.338000+00:00  at org.apache.logging.log4j.core.impl.ReusableLogEventFactory.release(ReusableLogEventFactory.java:141)
2023-12-15T11:26:15.338000+00:00  at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:578)
2023-12-15T11:26:15.338000+00:00  at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:92)
2023-12-15T11:26:15.338000+00:00  at org.apache.logging.log4j.core.Logger.log(Logger.java:169)
2023-12-15T11:26:15.338000+00:00  at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2933)
2023-12-15T11:26:15.338000+00:00  at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2886)
2023-12-15T11:26:15.338000+00:00  at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2868)
2023-12-15T11:26:15.338000+00:00  at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2647)
2023-12-15T11:26:15.338000+00:00  at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2594)
2023-12-15T11:26:15.339000+00:00  at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1597)
2023-12-15T11:26:15.339000+00:00  at dev.restate.sdk.examples.Greeter.greet(Greeter.kt:31)
[... My application stacktrace ...]
2023-12-15T11:26:15.340000+00:00  at dev.restate.sdk.lambda.BaseRestateLambdaHandler.handleRequest(BaseRestateLambdaHandler.java:28)
2023-12-15T11:26:15.340000+00:00  at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:202)
2023-12-15T11:26:15.340000+00:00  at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$2.call(EventHandlerLoader.java:905)
2023-12-15T11:26:15.340000+00:00  at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:245)
2023-12-15T11:26:15.340000+00:00  at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:197)
2023-12-15T11:26:15.340000+00:00  at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:187)

```

### PR DESCRIPTION
**Pull request by ppkarwasz**
This PR marks `StringMap`s generated from Java `Map`s as frozen if the wrapped map is immutable.

Fixes #2098

### CODE REVIEW

File: log4j-core/src/main/java/org/apache/logging/log4j/core/impl/JdkMapAdapterStringMap.java [hunk 1]
```diff
@@ -52,6 +52,11 @@ public JdkMapAdapterStringMap() {
 
     public JdkMapAdapterStringMap(final Map<String, String> map) {
         this.map = Objects.requireNonNull(map, "map");
+        try {
+            map.replace(Strings.EMPTY, Strings.EMPTY, Strings.EMPTY);
+        } catch (final UnsupportedOperationException ignored) {
+            immutable = true;
+        }
```
Comment (vy) [inline log4j-core/src/main/java/org/apache/logging/log4j/core/impl/JdkMapAdapterStringMap.java:59]: Why don't we simply do `this.map = new HashMap<>(map)`? Checking against `Map#replace()` implies that `Map#replace()` is the only effect expected to be used and a future change to this contract will cause similar issues again.

Comment (ppkarwasz) [reply log4j-core/src/main/java/org/apache/logging/log4j/core/impl/JdkMapAdapterStringMap.java:59]: All the immutable maps in JDK (`Collections` and `ImmutableCollections`) I found throw on `Map#replace`.

I get your point, but I think the chances this issue resurfaces in the future, because an implementation allows `Map#replace` but does not implement other methods, is slim.
Adding `new HashMap` will incur in an allocation even if the map is already mutable.

Comment (vy) [reply log4j-core/src/main/java/org/apache/logging/log4j/core/impl/JdkMapAdapterStringMap.java:59]: I won't object the change, but I wouldn't implement this myself. It is a bet for an unsolicited optimization.
