### PR TITLE
Fix Android-related issues in Log4j Core

### LINKED ISSUE #3056: Error using log4j2 api/core libraries with Android
## Description

Using log4j2 v2.24.0 (api and core) with Android throws error:

    I/com.example: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/data/app/~~MLF2ZshZzBIhJrgJjHw41g==/com.example-3Fbkjvp4obnGh8xK-dY_6A==/base.apk"],nativeLibraryDirectories=[/data/app/~~MLF2ZshZzBIhJrgJjHw41g==/com.example-3Fbkjvp4obnGh8xK-dY_6A==/lib/x86, /data/app/~~MLF2ZshZzBIhJrgJjHw41g==/com.example-3Fbkjvp4obnGh8xK-dY_6A==/base.apk!/lib/x86, /system/lib, /system_ext/lib]

gradle settings:

    implementation ('org.apache.logging.log4j:log4j-api:2.24.1'){
        exclude group: 'com.sun.jmx', module: 'jmx'
        exclude group: 'javax.management'
    }
    implementation 'org.apache.logging.log4j:log4j-core:2.24.1'

## Configuration

**Version:** 2.24.0

**Operating system:** Android SDK34

**JDK:** 1.8

## Logs
    I/com.example: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/data/app/~~MLF2ZshZzBIhJrgJjHw41g==/com.example-3Fbkjvp4obnGh8xK-dY_6A==/base.apk"],nativeLibraryDirectories=[/data/app/~~MLF2ZshZzBIhJrgJjHw41g==/com.example-3Fbkjvp4obnGh8xK-dY_6A==/lib/x86, /data/app/~~MLF2ZshZzBIhJrgJjHw41g==/com.example-3Fbkjvp4obnGh8xK-dY_6A==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]

### PR DESCRIPTION
**Pull request by ppkarwasz**
This fixes three issues encountered in the [`log4j-samples-android`](https://github.com/apache/logging-log4j-samples/tree/main/log4j-samples-android) test project:

1. Disables the `jvmrunargs` lookup on Android and fixes it on the other platforms. Previously, the lookup always returned `null`.
2. Switches the default context selector to `BasicContextSelector` on Android. `StackLocator` is broken on Android: it cannot use our JDK 8 code (missing `sun.reflect` classes), but also it cannot use our JDK 11+ code (missing multi-release JAR support). This causes `ClassLoaderContextSelector` to use two different logger contexts for the same classloader.
3. Fixes a `ParserConfigurationException` caused by the lack of XInclude capabilities in Android's XML parser. The fix to [LOG4J2-3531](https://issues.apache.org/jira/browse/LOG4J2-3531) didn't cover all the cases.

Closes #3056.
Part of #2832.

### CODE REVIEW

File: log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/JmxRuntimeInputArgumentsLookup.java [hunk 1]
```diff
@@ -31,17 +34,16 @@
...
+    private static final Logger LOGGER = StatusLogger.getLogger();
 
-    public static final JmxRuntimeInputArgumentsLookup JMX_SINGLETON;
+    public static final JmxRuntimeInputArgumentsLookup JMX_SINGLETON = new JmxRuntimeInputArgumentsLookup();
 
     /**
      * Constructor when used directly as a plugin.
      */
-    public JmxRuntimeInputArgumentsLookup() {}
+    public JmxRuntimeInputArgumentsLookup() {
```
Comment (vy) [inline log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/JmxRuntimeInputArgumentsLookup.java:44]: *Nit:* Can't we instead have a `@PluginFactory` returning the singleton instance?

**Review by vy — APPROVED** [review]
LGTM. :+1:

I would also like to see a F.A.Q. entry for Android (e.g., `Does Log4j Core work on Android?`) and document that

* Yes, it works out-of-the-box
* XInclude is not available
* `BasicContextSelector` [link to `BCS` docs] will be used

File: log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/JmxRuntimeInputArgumentsLookup.java (hunk 1 above)
Comment (ppkarwasz) [reply log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/JmxRuntimeInputArgumentsLookup.java:44]: This is not possible, since lookups are instantiated through a public no-arg constructor:

https://github.com/apache/logging-log4j2/blob/ab0fdbc51742646144f6ad29715f9bd1d9afa985/log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/Interpolator.java#L84-L95

**Comment by ppkarwasz** [comment]
@vy,

I added a FAQ entry in https://github.com/apache/logging-log4j2/pull/3071/commits/fbd4ea0c048ec66902f2dd6e13318636cb99966c.

Since this PR can not be tested, until we publish a snapshot and the external [`android-test.yaml`](https://github.com/apache/logging-log4j-samples/actions/workflows/android-test.yaml) action succeeds, I am merging this PR.
Feel free to improve the doc on `2.x`.

**Comment by ppkarwasz** [comment]
The [CI build 11273365001](https://github.com/apache/logging-log4j2/actions/runs/11273365001) confirms that a simple application on Android functions correctly with Log4j Core.

**Comment by ahasbini** [comment]
When will this merge be released?

**Comment by ppkarwasz** [comment]
@ahasbini,

Please open a [GitHub Discussion](https://github.com/apache/logging-log4j2/discussions) or ask on [the `log4j-user@logging` mailing list](https://logging.apache.org/support.html#discussions-user) (preferred way: not all maintainers follow GH Discussions).

Personally I won't have time to make a `2.25.0` release before January 2025, but other maintainers might do it.
