### PR TITLE
Reopen log file when rollover is unsuccessful

### LINKED ISSUE #2592: After a log file is deleted by mistake, a new rollover file cannot be created.
## Description

In earlier versions, such as 2.18.0, even if log files are deleted accidentally, the deleted files are automatically generated when the rollback conditions are met.
But now, it doesn't work when we use log4j 2.23.1.

name: ROLLING_FILE
      policies:
        sizeBasedTriggeringPolicy: {size: 100MB}
        timebasedtriggeringpolicy: {interval: '1'}

## Configuration
**Version:** [Log4j version]
2.23.1
**Operating system:** [OS and version]
linux
**JDK:** [JDK distribution and version]
JDK8
## Logs
```
 ERROR Unable to write to stream /opt/logs/app/app-system.log for appender ROLLING_FILE org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to stream /opt/logs/app/app-system.log
        at org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:265)
        at org.apache.logging.log4j.core.appender.FileManager.writeToDestination(FileManager.java:335)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.writeToDestination(RollingFileManager.java:385)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:296)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:307)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:229)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:220)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:211)
        at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:337)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:705)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:663)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:639)
        at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:696)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:665)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:639)
        at org.apache.logging.log4j.core.async.AsyncLoggerConfig.log(AsyncLoggerConfig.java:154)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:540)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:67)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:155)
        at org.apache.logging.log4j.spi.ExtendedLoggerWrapper.logMessage(ExtendedLoggerWrapper.java:281)
        ...
        at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:234)
        at com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:105)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Stream Closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:263)
        ... 37 more
```

## Reproduction

This commit :  https://github.com/apache/logging-log4j2/commit/3bc608db0de95690ea0a75e2f6a290d9418d7bbc
RollingFileManager      private boolean rollover(final RolloverStrategy strategy)
 before:  return true  ---> Now: return success;
After we rollback this change , it works.

### PR DESCRIPTION
**Pull request by king-tyler**
Fixes https://github.com/apache/logging-log4j2/issues/2592
Fixes `RollingFileManager` to reopen the log file when the rollover was unsuccessful

See also https://github.com/apache/logging-log4j2/pull/3021#issuecomment-2392077718

## Checklist

* Base your changes on `2.x` branch if you are targeting Log4j 2; use `main` otherwise
* `./mvnw verify` succeeds (if it fails due to code formatting issues reported by Spotless, simply run `./mvnw spotless:apply` and retry)
* Non-trivial changes contain an entry file in the `src/changelog/.2.x.x` directory
* Tests for the changes are provided
* [Commits are signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (optional, but highly recommended)

### CODE REVIEW

File: log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/RollingFileManager.java [hunk 1]
```diff
@@ -506,9 +506,16 @@ public synchronized void rollover() {
...
                     createFileAfterRollover();
+                    final File file = new File(getFileName());
+                    size = file.length();
+                    try {
+                        final FileTime creationTime = (FileTime) Files.getAttribute(file.toPath(), "creationTime");
+                        initialTime = creationTime.toMillis();
+                    } catch (Exception ex) {
+                        LOGGER.warn("Unable to get current file time for {}", file);
+                        initialTime = System.currentTimeMillis();
+                    }
```
Comment (ppkarwasz) [inline log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/RollingFileManager.java:518]: - Even if the rollover fails, I would still reset the `size` field. This is the field used by [`SizeBasedTriggeringPolicy`](https://logging.apache.org/log4j/3.x/manual/appenders/rolling-file.html#SizeBasedTriggeringPolicy) to determine, when a rollover is due. Otherwise the triggering policy might attempt a rollover at **each** log event. It is safe to assume that the new rollover might fail too.
- The `initialTime` field is not really used by any triggering policy at runtime. It is only used at **configuration time** and never queried again. I would leave it as is.

File: log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/RollingFileManager.java [hunk 2]
```diff
@@ -636,7 +643,7 @@ private boolean rollover(final RolloverStrategy strategy) {
                     asyncExecutor.execute(new AsyncAction(descriptor.getAsynchronous(), this));
                     releaseRequired = false;
                 }
-                return success;
+                return true;
```
Comment (ppkarwasz) [inline log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/RollingFileManager.java:646]: There are a lot of `boolean`s in this method with different purposes. It might be useful to rename them to make the code more clear. For example:

- `releaseRequired` actually tells us if the asynchronous action has started. Maybe we could rename it to `asyncActionStarted` and define it only where it is needed (just after the first `try`).
- `success` tells use if the synchronous action has succeeded. It should be rather called something like `syncActionSuccess` and be defined just before the synchronous action is executed.
- A third unnamed `boolean` is used in the return statements and there is no comment stating what `rollover(RolloverStrategy)` returns. I think we should introduce a `outputStreamClosed` variable that is defined at the beginning of the method and used in all the return statements. The lack of documentation is what caused #2592 in the first place.

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingFileManagerTest.java [hunk 3]
```diff
@@ -188,4 +193,40 @@ public void testCreateParentDir() {
...
+    @Test
+    @Issue("https://github.com/apache/logging-log4j2/issues/2592")
+    public void testRolloverOfDeletedFile() throws IOException {
+        final Configuration configuration = new NullConfiguration();
+        final File file = File.createTempFile("testRolloverOfDeletedFile", "log");
+        file.deleteOnExit();
+        final String testContent = "Test";
+        try (final OutputStream os =
+                        new ByteArrayOutputStream(); // use a dummy OutputStream so that the real file can be deleted
+                final RollingFileManager manager = new RollingFileManager(
```
Comment (ppkarwasz) [inline log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingFileManagerTest.java:206]: Nice test! :100:

By calling the constructor directly, you prevent the registration of `RollingFileManager` in the registry kept by `AbstractManager`. This a very nice approach for tests!

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingFileManagerTest.java [hunk 4]
```diff
@@ -188,4 +193,40 @@ public void testCreateParentDir() {
...
+                        "testRolloverOfDeletedFile.log.%d{yyyy-MM-dd}",
+                        os,
+                        true,
+                        false,
+                        0,
+                        System.currentTimeMillis(),
+                        OnStartupTriggeringPolicy.createPolicy(1),
+                        DefaultRolloverStrategy.newBuilder().build(),
+                        file.getName(),
+                        PatternLayout.createDefaultLayout(configuration),
```
Comment (ppkarwasz) [inline log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingFileManagerTest.java:218]: Both the `LoggerContext` and `Layout` parameters can actually be `null`. This way you don't need the rather expensive `Configuration` object.

**Review by ppkarwasz — CHANGES_REQUESTED** [review]
@king-tyler,

Thank you for your PR. It certainly solves the #2592 issue, but I would take the opportunity to clarify some `RollingFileManager` code.

IMHO, the code of the rolling file appenders is very unclear and hard to maintain, which is the cause of the multitude of bug reports for this component.

**Review by ppkarwasz — APPROVED** [review]

**Comment by ppkarwasz** [comment]
@king-tyler,

Thank You for your contribution! :100:
