### PR TITLE
Stabilize `RollingAppenderDeleteAccumulatedCount1Test`

### LINKED ISSUE #3003: RollingAppenderDeleteAccumulatedCount1Test is unreliable
## Description

RollingAppenderDeleteAccumulatedCount1Test is unreliable

```
RollingAppenderDeleteAccumulatedCount1Test.testAppender:84 [target\rolling-with-delete-accum-count1\test\my-1.log, target\rolling-with-delete-accum-count1\test\my-2.log, target\rolling-with-delete-accum-count1\test\my-3.log, target\rolling-with-delete-accum-count1\test\my-4.log, target\rolling-with-delete-accum-count1\test\my-5.log, target\rolling-with-delete-accum-count1\test\test-3.log, target\rolling-with-delete-accum-count1\test\test-4.log, target\rolling-with-delete-accum-count1\test\test-5.log, target\rolling-with-delete-accum-count1\test\test-6.log, target\rolling-with-delete-accum-count1\test\test-7.log, target\rolling-with-delete-accum-count1\test\test-8.log, target\rolling-with-delete-accum-count1\test\test-9.log] expected:<11> but was:<12>
```

## Configuration

**Version:** 2.x at 01125b11a7c52af12204a1c4a646158f63b2d6eb

**Operating system:** 
Microsoft Windows [Version 10.0.19045.4780

**JDK:** 
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: C:\java\apache-maven-3.9.9
Java version: 17.0.12, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-17.0.12.7-hotspot
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
## Logs

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.260 s <<< FAILURE! -- in org.apache.logging.log4j.core.appender.rolling.RollingAppenderDeleteAccumulatedCount1Test
[ERROR] org.apache.logging.log4j.core.appender.rolling.RollingAppenderDeleteAccumulatedCount1Test.testAppender -- Time elapsed: 3.223 s <<< FAILURE!
java.lang.AssertionError: [target\rolling-with-delete-accum-count1\test\my-1.log, target\rolling-with-delete-accum-count1\test\my-2.log, target\rolling-with-delete-accum-count1\test\my-3.log, target\rolling-with-delete-accum-count1\test\my-4.log, target\rolling-with-delete-accum-count1\test\my-5.log, target\rolling-with-delete-accum-count1\test\test-3.log, target\rolling-with-delete-accum-count1\test\test-4.log, target\rolling-with-delete-accum-count1\test\test-5.log, target\rolling-with-delete-accum-count1\test\test-6.log, target\rolling-with-delete-accum-count1\test\test-7.log, target\rolling-with-delete-accum-count1\test\test-8.log, target\rolling-with-delete-accum-count1\test\test-9.log] expected:<11> but was:<12>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.apache.logging.log4j.core.appender.rolling.RollingAppenderDeleteAccumulatedCount1Test.testAppender(RollingAppenderDeleteAccumulatedCount1Test.java:84)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.apache.logging.log4j.core.test.junit.LoggerContextRule$1.evaluate(LoggerContextRule.java:136)

```

## Reproduction

```
mvn clean install
```

### PR DESCRIPTION
**Pull request by rjuare8**
Stabilize `RollingAppenderDeleteAccumulatedCount1Test`.

Fixes #3003.

### CODE REVIEW

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderDeleteAccumulatedCount1Test.java [hunk 1]
```diff
@@ -67,24 +71,37 @@ public void testAppender() throws Exception {
...
         final File dir = new File(DIR);
         assertTrue("Dir " + DIR + " should exist", dir.exists());
-        assertTrue("Dir " + DIR + " should contain files", dir.listFiles().length > 0);
 
-        final File[] files = dir.listFiles();
-        for (final File file : files) {
-            System.out.println(file + " (" + file.length() + "B) "
-                    + FixedDateFormat.create(FixedFormat.ABSOLUTE).format(file.lastModified()));
-        }
+        // Wait until the directory contents stabilize (no size change across two polls)
```
Comment (vy) [inline log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderDeleteAccumulatedCount1Test.java]: 1. You don't need `Thread.sleep()`, you can remove it. (Awaitility already polls.)
2. Don't wait until contents stabilize, instead, wait until what you want to verify succeeds. That is, place the entire check logic there.
3. Sign all your commits

**Review by vy — CHANGES_REQUESTED** [review]

**Comment by rjuare8** [comment]
Added requested changes and signed all commits! Let me know if I need to take additional actions for this PR.

**Review by vy — APPROVED** [review]
