### PR TITLE
Fix issue #2380: Log messages with insufficient parameters should not throw exception.

### LINKED ISSUE #2380: Log messages with partially missing parameters
Log4j version `2.20.0` did also log messages with missing parameters. A call like:

```java
logger.info("{}, {} and {}", 1, 2);
```

resulted in a partially replaced message: `1, 2, and {}`.

The behavior changed in `2.21.0` and should be restored for backward compatibility.

### PR DESCRIPTION
**Pull request by SeasonPanPan**
Fix issue #2380: Log messages with insufficient parameters should not throw exception.

In this PR, I modified the class `org.apache.logging.log4j.message.ParameterFormatter`.
I deleted the codes about checking placeholderCount and argCount, if they weren't equal, it would throw an IllegalArgumentException. 

At the same time, I also modified the corresponding test cases.

Close #2380

@ppkarwasz Please review the codes when you have time.

### CODE REVIEW

File: log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java [hunk 1]
```diff
@@ -240,14 +240,6 @@ static void formatMessage(
             return;
         }
 
-        // Fail if there are insufficient arguments
-        if (analysis.placeholderCount > args.length) {
-            final String message = String.format(
-                    "found %d argument placeholders, but provided %d for pattern `%s`",
-                    analysis.placeholderCount, args.length, pattern);
-            throw new IllegalArgumentException(message);
-        }
```
Comment (ppkarwasz) [inline log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java:249]: I would prefer to issue a `StatusLogger` warning whenever the number of arguments:

- is less than `analysis.placeholderCount` (some arguments are missing),
- is higher than `analysis.placeholderCount + (args[args.length - 1] instance of Throwable ? 1 : 0)` (some arguments will be ignored).

Since there will be no more exceptions throws, you can remove the `try...catch`es at the call sites.

Comment (SeasonPanPan) [reply log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java:249]: I got your point, I'm modifying the codes.

Comment (vy) [reply log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java:249]: Agreed with @ppkarwasz's remark. Please provide sufficient test coverage for all possibilities he shared. In particular, test not just the unhappy flow, but also happy flow.

**Review by vy — CHANGES_REQUESTED** [review]
I see several tests being replaced by single-shot examples, please don't. Instead use a `@ParameterizedTest` and provide several examples providing sufficient coverage. I also would like to see examples where arguments contain `Throwable`s to match against the cases @ppkarwasz stated.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java [hunk 2]
```diff
@@ -68,15 +67,12 @@ void test_pattern_analysis(
...
 
-    @ParameterizedTest
-    @CsvSource({"1,foo {}", "2,bar {}{}"})
-    void format_should_fail_on_insufficient_args(final int placeholderCount, final String pattern) {
-        final int argCount = placeholderCount - 1;
-        assertThatThrownBy(() -> ParameterFormatter.format(pattern, new Object[argCount], argCount))
-                .isInstanceOf(IllegalArgumentException.class)
-                .hasMessage(
-                        "found %d argument placeholders, but provided %d for pattern `%s`",
-                        placeholderCount, argCount, pattern);
```
Comment (ppkarwasz) [inline log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:79]: While we don't provide an equivalent `assertThatLoggedBy` method to test that a certain status logger message was issued (we probably should), you can add an `org.apache.logging.log4j.Logger statusLogger` parameter to `ParameterFormatter.format` and detect status messages as in [`ProviderUtilTest`](https://github.com/apache/logging-log4j2/blob/ed4c72e679951fe78fe4121436085444bc87b388/log4j-api-test/src/test/java/org/apache/logging/log4j/util/ProviderUtilTest.java).

Comment (vy) [reply log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:79]: No, this is not needed. This file was already testing logged `StatusLogger` messages – scroll down, you will see the associated @SeasonPanPan deleted. They need to simply revert those changes and adapt them accordingly.

Comment (SeasonPanPan) [reply log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterFormatterTest.java:79]: Yes, I find the codes to check status logger what I deleted. I am adding the test cases.

**Comment by SeasonPanPan** [comment]
@vy @ppkarwasz Done, and added some test cases with the following scenarios:  
      
     * 1. The placeholders are greater than the count of arguments. 
     * 2. The placeholders are less than the count of arguments.  
     * 3. The arguments contains an exception, and the placeholder is greater than normal arguments. 
     * 4. The arguments contains an exception, and the placeholder is less than the arguments. 
     All of these should logged in status logger with WARN level.
 
But this case with no warn log:
*  The arguments contains an exception, and the placeholder count is equal to normal arguments.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterizedMessageTest.java [hunk 3]
```diff
@@ -185,16 +185,73 @@ void testSerializable(final Object arg) {
...
+                new Object[] {"more {} {}", 2, new Object[] {"a"}, "more a {}"},
+                new Object[] {"more {} {} {}", 3, new Object[] {"a"}, "more a {} {}"},
+                new Object[] {"less {}", 1, new Object[] {"a", "b"}, "less a"},
+                new Object[] {"less {} {}", 2, new Object[] {"a", "b", "c"}, "less a b"},
+                new Object[] {
+                    "more throwable {} {}",
+                    2,
+                    new Object[] {"a", new RuntimeException()},
+                    "more throwable a java.lang.RuntimeException"
+                },
```
Comment (ppkarwasz) [inline log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterizedMessageTest.java:236]: This case should issue no warning: the `RuntimeException` is simply classified as normal argument and it fills the second placeholder.

**Review by ppkarwasz — CHANGES_REQUESTED** [review]
Nice job!

It almost looks good to me, except we need to maintain Log4j semantics (which is the same as Logback < 1.1.0 semantics) for classifying a trailing `Throwable` as part of the arguments or as "extra" argument.

File: log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java [hunk 4]
```diff
@@ -240,12 +244,14 @@ static void formatMessage(
...
+        // check if there are insufficient arguments that do not include Throwable arg
+        final int realArgCount = args.length;
+        final int noThrowableArgCount = realArgCount - ((args[realArgCount - 1] instanceof Throwable) ? 1 : 0);
+        if (analysis.placeholderCount != noThrowableArgCount) {
             final String message = String.format(
                     "found %d argument placeholders, but provided %d for pattern `%s`",
-                    analysis.placeholderCount, args.length, pattern);
-            throw new IllegalArgumentException(message);
+                    analysis.placeholderCount, realArgCount, pattern);
+            STATUS_LOGGER.warn(message);
```
[the remark this answers is not in the document]
Comment (SeasonPanPan) [reply log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java:254]: Yes, yours is good example.

File: log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterizedMessageTest.java (hunk 3 above)
Comment (SeasonPanPan) [reply log4j-api-test/src/test/java/org/apache/logging/log4j/message/ParameterizedMessageTest.java:236]: I will adjust this case.

File: log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java [hunk 5]
```diff
@@ -240,12 +244,14 @@ static void formatMessage(
             return;
         }
 
-        // Fail if there are insufficient arguments
-        if (analysis.placeholderCount > args.length) {
+        // check if there are insufficient arguments that do not include Throwable arg
+        final int realArgCount = args.length;
+        final int noThrowableArgCount = realArgCount - ((args[realArgCount - 1] instanceof Throwable) ? 1 : 0);
+        if (analysis.placeholderCount != noThrowableArgCount) {
```
[the remark this answers is not in the document]
Comment (ppkarwasz) [reply log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java:250]: Ah, you mean that code like:

```java
logger.info("An error in {} occurred: {}", "foo", new RuntimeException());
```

should give a warning? I might agree that it should give a warning, since such statements prevent users from switching to Logback in the future. However for backward compatibility, such statements should be silently accepted.

@vy, what do you think?

[the remark this answers is not in the document]
Comment (SeasonPanPan) [reply log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java:250]: Please confirm if I need to give a warning log. I will change my codes or not. @vy @ppkarwasz

File: log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java [hunk 6]
```diff
@@ -240,12 +244,17 @@ static void formatMessage(
...
-        // Fail if there are insufficient arguments
-        if (analysis.placeholderCount > args.length) {
-            final String message = String.format(
-                    "found %d argument placeholders, but provided %d for pattern `%s`",
-                    analysis.placeholderCount, args.length, pattern);
-            throw new IllegalArgumentException(message);
+        // #2380: check if the count of placeholder is not equal to the count of arguments
+        if (analysis.placeholderCount != argCount) {
+            final int realArgCount = args.length;
+            final int noThrowableArgCount = realArgCount - ((args[realArgCount - 1] instanceof Throwable) ? 1 : 0);
```
Comment (ppkarwasz) [inline log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java:250]:
```suggestion
            final int noThrowableArgCount = realArgCount - ((args[argCount - 1] instanceof Throwable) ? 1 : 0);
```

Use `argCount` instead of `args.length`: the array can have an arbitrary length (it can be reused by multiple messages), that is why the method accepts `argCount` as argument.

**Review by ppkarwasz — APPROVED** [review]
Apart from the usage of `args.length`, it looks good to me.

**Comment by SeasonPanPan** [comment]
> Apart from the usage of `args.length`, it looks good to me.

Done. Because the argCount might be 0 in ReusableMessage, I made a non-zero judgment in advance.

**Comment by ppkarwasz** [comment]
@SeasonPanPan

Thank you for your contribution.
