### PR TITLE
Stabilize `RollingAppenderDirectCronTest` and `XmlCompleteFileAppenderTest`

### LINKED ISSUE #3046: RollingAppenderDirectCronTest.testAppender(LoggerContext, RollingFileAppender) is unreliable
## Description

RollingAppenderDirectCronTest.testAppender(LoggerContext, RollingFileAppender) is unreliable:
```
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.52 s -- in org.apache.logging.log4j.core.appender.TlsSyslogAppenderTest
17:14:12.956 main ERROR The handler cannot be set to null
2024-10-01T21:14:13.119566500Z main ERROR Test `testAppender(LoggerContext, RollingFileAppender)` has failed, dumping status data... java.lang.AssertionError:
Expecting actual not to be empty
        at org.apache.logging.log4j.core.appender.rolling.RollingAppenderDirectCronTest$RolloverDelay.rolloverComplete(RollingAppenderDirectCronTest.java:107)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.rollover(RollingFileManager.java:524)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.rollover(RollingFileManager.java:479)
        at org.apache.logging.log4j.core.appender.rolling.CronTriggeringPolicy.rollover(CronTriggeringPolicy.java:153)
        at org.apache.logging.log4j.core.appender.rolling.CronTriggeringPolicy.access$100(CronTriggeringPolicy.java:40)
        at org.apache.logging.log4j.core.appender.rolling.CronTriggeringPolicy$CronTrigger.run(CronTriggeringPolicy.java:176)
        at org.apache.logging.log4j.core.config.ConfigurationScheduler$CronRunnable.run(ConfigurationScheduler.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

## Configuration

**Version:**
```
commit ad3c03d231913bfc9d613de91408c61649cc6d60 (HEAD -> 2.x, origin/2.x)
Author: Volkan Yazıcı <volkan@yazi.ci>
Date:   Tue Oct 1 21:09:31 2024 +0200

    Fix Awaitility usage in `SocketAppenderReconnectTest` (#3004)
```

**Operating system:** 
```
Microsoft Windows [Version 10.0.19045.4780]
```

**JDK:**
```
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment Temurin-17.0.12+7 (build 17.0.12+7)
OpenJDK 64-Bit Server VM Temurin-17.0.12+7 (build 17.0.12+7, mixed mode, sharing)
```
```
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: C:\java\apache-maven-3.9.9
Java version: 17.0.12, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-17.0.12.7-hotspot
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

## Logs

https://gist.github.com/garydgregory/2e982c9d0bb1e56457ec1984eff9d30e

## Reproduction
```
cls && git log -1 && mvn clean verify
```

### PR DESCRIPTION
**Pull request by rjuare8**
Stabilize `RollingAppenderDirectCronTest`.

Fixes #3046.

### CODE REVIEW

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderDirectCronTest.java [hunk 1]
```diff
@@ -102,16 +102,18 @@ public void rolloverComplete(final String fileName) {
...
-                } catch (final IOException ex) {
-                    fail("Unable to read file " + fileName + ": " + ex.getMessage());
-                }
+
+                // Wait until the file is non-empty (or timeout)
+                waitAtMost(2, TimeUnit.SECONDS).until(() -> Files.exists(path) && Files.size(path) > 0);
+
+                final List<String> lines = Files.readAllLines(path);
+                assertThat(lines).isNotEmpty();
+                assertThat(lines.get(0)).startsWith(matcher.group(1));
```
Comment (vy) [inline log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderDirectCronTest.java]: Could you instead move the assertion block inside a `waitAtMost(Duration.ofSeconds(5)).untilAsserted(...)`, please?

**Comment by vy** [comment]
@rjuare8, thanks for the contribution. Would you mind performing the following tasks, please?

1. [Sign your commits](https://chatgpt.com/share/689f0f3a-22b8-8002-90d7-6b7c1d702ffa)
2. Run `./mvnw spotless:apply -pl :log4j-core-test`
3. Ensure `./mvnw verify -pl :log4j-core-test` passes
4. Read [the Log4j Development Guide](https://github.com/apache/logging-log4j2/blob/2.x/BUILDING.adoc#development)

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/XmlCompleteFileAppenderTest.java
Comment (vy) [inline log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/XmlCompleteFileAppenderTest.java:1]: Does this serve any purpose related with the `RollingAppenderDirectCronTest` fix? If not, please revert this incidental change.

**Comment by vy** [comment]
@rjuare8, **all your commits** must be signed, and they are not. See the [Commits](https://github.com/apache/logging-log4j2/pull/3946/commits) tab and `Unverified` labels there.

**Comment by rjuare8** [comment]
Signed all my commits! Let me know if there is additional actions I need to take.


Related to my fix for `testFlushAtEndOfBatch()`. This change hardens `XmlCompleteFileAppenderTest#testFlushAtEndOfBatch` against formatting/timing variance where a blank line after the `<Events>` root element is not guaranteed. The prior test unconditionally consumed one line after `<Events>`, assuming it was always blank; when the blank line was absent, the `<Event …> `line was skipped and later assertions occasionally saw `line3 == null`.

**Review by vy — APPROVED** [review]

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/XmlCompleteFileAppenderTest.java
Comment (vy) [reply log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/XmlCompleteFileAppenderTest.java:1]: Explained in another thread: https://github.com/apache/logging-log4j2/pull/3946#issuecomment-3429569835

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderDirectCronTest.java (hunk 1 above)
Comment (vy) [reply log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderDirectCronTest.java]: After waiting for 2 weeks, implemented myself in 6fbd257b8.

**Comment by vy** [comment]
> Signed all my commits! Let me know if there is additional actions I need to take.

Yes, there ~are~ were: https://github.com/apache/logging-log4j2/pull/3946#discussion_r2418816253 Since it was 2 weeks ago, I have decided to address it myself in 6fbd257b8. While I really appreciate your contribution, I'd very glad if you can read and address all review remarks next time.

**Review by vy — APPROVED** [review]
