### PR TITLE
Replace fixed delay with polling in `SyslogAppenderCustomLayoutTest`

### LINKED ISSUE #3006: SyslogAppenderCustomLayoutTest is unreliable
## Description

SyslogAppenderCustomLayoutTest is unreliable

```
[ERROR] Failures:
[ERROR]   SyslogAppenderCustomLayoutTest>SyslogAppenderTest.testTCPAppender:56->SyslogAppenderTestBase.sendAndCheckLegacyBsdMessage:74->SyslogAppenderTestBase.checkTheNumberOfSentAndReceivedMessages:112 The number of received messages should be equal with the number of sent messages expected:<1> but was:<0>
[ERROR]   SyslogAppenderCustomLayoutTest>SyslogAppenderTest.testUDPAppender:79->SyslogAppenderTestBase.sendAndCheckLegacyBsdMessage:74->SyslogAppenderTestBase.checkTheNumberOfSentAndReceivedMessages:112 The number of received messages should be equal with the number of sent messages expected:<1> but was:<0>
```

## Configuration

**Version:** 2.x at 01125b11a7c52af12204a1c4a646158f63b2d6eb

**Operating system:** 
Microsoft Windows [Version 10.0.19045.4780

**JDK:** 
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: C:\java\apache-maven-3.9.9
Java version: 17.0.12, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-17.0.12.7-hotspot
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

## Logs

```
[ERROR] Tests run: 5, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 3.549 s <<< FAILURE! -- in org.apache.logging.log4j.core.appender.SyslogAppenderCustomLayoutTest
[INFO] Running org.apache.logging.log4j.core.appender.SmtpAppenderAsyncTest
10:07:11.688 main ERROR The pattern, literal, and isEventTimestamp attributes are mutually exclusive.
[ERROR] org.apache.logging.log4j.core.appender.SyslogAppenderCustomLayoutTest.testTCPAppender -- Time elapsed: 0.225 s <<< FAILURE!
java.lang.AssertionError: The number of received messages should be equal with the number of sent messages expected:<1> but was:<0>
        at org.apache.logging.log4j.core.appender.SyslogAppenderTestBase.checkTheNumberOfSentAndReceivedMessages(SyslogAppenderTestBase.java:112)
        at org.apache.logging.log4j.core.appender.SyslogAppenderTestBase.sendAndCheckLegacyBsdMessage(SyslogAppenderTestBase.java:74)
        at org.apache.logging.log4j.core.appender.SyslogAppenderTest.testTCPAppender(SyslogAppenderTest.java:56)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[ERROR] org.apache.logging.log4j.core.appender.SyslogAppenderCustomLayoutTest.testUDPAppender -- Time elapsed: 0.209 s <<< FAILURE!
java.lang.AssertionError: The number of received messages should be equal with the number of sent messages expected:<1> but was:<0>
        at org.apache.logging.log4j.core.appender.SyslogAppenderTestBase.checkTheNumberOfSentAndReceivedMessages(SyslogAppenderTestBase.java:112)
        at org.apache.logging.log4j.core.appender.SyslogAppenderTestBase.sendAndCheckLegacyBsdMessage(SyslogAppenderTestBase.java:74)
        at org.apache.logging.log4j.core.appender.SyslogAppenderTest.testUDPAppender(SyslogAppenderTest.java:79)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

## Reproduction

```
mvn clean install
```

### PR DESCRIPTION
**Pull request by Kcruz28**
This PR fixes a flaky test that was failing because of a race condition.

This pull request addresses intermittent test failures caused by relying on a fixed delay `Thread.sleep()` to wait for asynchronous operations. Fixed delays are unreliable because the operation may occasionally take longer than the predefined wait time.

This commit replaces the fixed delay with a polling mechanism using the Awaitility library. Awaitility continuously checks for the expected condition within a specified timeout, ensuring the test only proceeds once the desired state is reached. This makes the test more robust and reliable by synchronizing with actual operation completion rather than arbitrary timing.

Fixes #3006

> [!IMPORTANT]  
> Base your changes on `2.x` branch if you are targeting Log4j 2; use `main` otherwise.

## Checklist

Before we can review and merge your changes, please go through the checklist below. If you're still working on some items, feel free to submit your pull request as a draft—our CI will help guide you through the remaining steps.

### ✅ Required checks

- [x] **License**: I confirm that my changes are submitted under the [Apache License, Version 2.0](https://apache.org/licenses/LICENSE-2.0).
- [x] **Commit signatures**: All commits are signed and verifiable. (See [GitHub Docs on Commit Signature Verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)).
- [x] **Code formatting**: The code is formatted according to the project’s style guide.
  <details>
    <summary>How to check and fix formatting</summary>

    - To **check** formatting: `./mvnw spotless:check`
    - To **fix** formatting: `./mvnw spotless:apply`

    See [the build instructions](https://logging.apache.org/log4j/2.x/development.html#building) for details.
  </details>
- [x] **Build & Test**: I verified that the project builds and all unit tests pass.
  <details>
    <summary>How to build the project</summary>

    Run: `./mvnw verify`

    See [the build instructions](https://logging.apache.org/log4j/2.x/development.html#building) for details.
  </details>

### 🧪 Tests (select one)

- [ ] I have added or updated tests to cover my changes.
- [x] No additional tests are needed for this change.

### 📝 Changelog (select one)

- [ ] I added a changelog entry in `src/changelog/.2.x.x`. (See [Changelog Entry File Guide](https://logging.apache.org/log4j/tools/log4j-changelog.html#changelog-entry-file)).
- [x] This is a trivial change and does not require a changelog entry.

### CODE REVIEW

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/SyslogAppenderTestBase.java [hunk 1]
```diff
@@ -43,13 +43,16 @@
...
+import static org.awaitility.Awaitility.await;
+
 @UsingStatusListener
 abstract class SyslogAppenderTestBase {
     protected static final String line1 =
             "TestApp - Audit [Transfer@18060 Amount=\"200.00\" FromAccount=\"123457\" ToAccount=\"123456\"]"
                     + "[RequestContext@18060 ipAddress=\"192.168.0.120\" loginId=\"JohnDoe\"] Transfer Complete";
     protected LoggerContext ctx = LoggerContext.getContext();
-    protected static final int DEFAULT_TIMEOUT_IN_MS = 100;
+    protected static final int DEFAULT_TIMEOUT_IN_MS = 500;
```
Comment (vy) [inline log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/SyslogAppenderTestBase.java]: We can be a little bit generous here, Awaitility's default poll period is 100ms anyway.

```suggestion
    protected static final int DEFAULT_TIMEOUT_IN_MS = 3000;
```

**Review by vy — APPROVED** [review]

**Comment by vy** [comment]
@Kcruz28, thanks for the fix. Would you mind signing your commits, please? If you need guidance for that, [ChatGPT responds well](
https://chatgpt.com/share/689f0f3a-22b8-8002-90d7-6b7c1d702ffa) to the following prompt:

> In a GitHub PR, how can I sign (not sign-off!) existing commits?

**Comment by vy** [comment]
I see that CI has failed due to styling issues. Please make sure to run `./mvnw spotless:apply -pl :log4j-core-test` and `./mvnw verify -pl :log4j-core-test`. I strongly advice you to read [the Log4j Development guide](https://github.com/apache/logging-log4j2/blob/2.x/BUILDING.adoc#development).

**Comment by Kcruz28** [comment]
I’ve signed my commits, and I believe I’ve fixed the styling issues. Please let me know if you encounter any problems.
