### PR TITLE
Fix state leakage in `AbstractAsyncThreadContextTestBase`

### LINKED ISSUE #3049: The test AsyncThreadContextDefaultTest is unreliable
## Description

The test `AsyncThreadContextDefaultTest` is unreliable:
```
...
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   AsyncThreadContextDefaultTest.testAsyncLogWritesToLog:38->AbstractAsyncThreadContextTestBase.testAsyncLogWritesToLog:188->AbstractAsyncThreadContextTestBase.checkResult:221 [Log file 'AsyncLoggerTest.log']
expected: "INFO c.f.Bar mapvalue [stackvalue] {KEY=mapvalue, configProp=configValue, configProp2=configValue2} WEBAPP DefaultThreadContextMap AsyncLoggerContext i=0"
 but was: "INFO c.f.Bar mapvalue [stackvalue, stackvalue] {KEY=mapvalue, configProp=configValue, configProp2=configValue2} WEBAPP DefaultThreadContextMap AsyncLoggerContext i=0"
[ERROR] Errors:
[ERROR]   AsyncThreadContextDefaultTest.testAsyncLogWritesToLog:38->AbstractAsyncThreadContextTestBase.testAsyncLogWritesToLog:176 » ConditionTimeout Condition with Lambda expression in org.apache.logging.log4j.core.async.AbstractAsyncThreadContextTestBase was not fulfilled within 500 milliseconds.
[INFO]
[ERROR] Tests run: 3786, Failures: 1, Errors: 1, Skipped: 33
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Log4j BOM 2.25.0-SNAPSHOT:
[INFO]
[INFO] Apache Log4j BOM ................................... SUCCESS [ 44.982 s]
[INFO] Apache Log4j Parent ................................ SUCCESS [  3.181 s]
[INFO] Apache Log4j API Java 9 support .................... SUCCESS [ 14.568 s]
[INFO] Apache Log4j API ................................... SUCCESS [ 40.655 s]
[INFO] Apache Log4j Implementation Java 9 support ......... SUCCESS [  8.318 s]
[INFO] Apache Log4j Core .................................. SUCCESS [01:58 min]
[INFO] Apache Log4j API Tests ............................. SUCCESS [01:30 min]
[INFO] Apache Log4j Core Tests ............................ FAILURE [10:36 min]
...
```

## Configuration

**Version:**
```
commit 38bc033443c85f9df68c9406fdacf32cb24d5143 (HEAD -> 2.x, origin/2.x)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue Oct 1 19:53:17 2024 +0000

    Update `com.google.guava:guava` to version `33.3.1-jre` (#3009)
```

**Operating system:** 
```
Microsoft Windows [Version 10.0.19045.4780]
```

**JDK:**
```
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment Temurin-17.0.12+7 (build 17.0.12+7)
OpenJDK 64-Bit Server VM Temurin-17.0.12+7 (build 17.0.12+7, mixed mode, sharing)
```
```
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: C:\java\apache-maven-3.9.9
Java version: 17.0.12, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-17.0.12.7-hotspot
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

## Logs

Full build console output: https://gist.github.com/garydgregory/90e31d986dfaa66d721c3e593c3240e9

## Reproduction

Run:
```
cls && git log -1 && mvn clean verify
```

### PR DESCRIPTION
**Pull request by Kcruz28**
`AsyncThreadContextDefaultTest` was a state leak. Since the test is parameterized, the `ThreadContext` wasn't being reset between runs. This meant data from a previous test execution could sometimes carry over and cause assertions in the next run to fail.

The fix is to ensure the `ThreadContext` is cleared before every test execution.

I added a `@BeforeEach` method to the shared base class, `AbstractAsyncThreadContextTestBase.java`. This new method simply calls `ThreadContext.clearAll()`, guaranteeing that each test starts with a clean slate.

This change prevents the state leak and makes the test reliable. Placing the fix in the base class also protects other tests that inherit from it against similar issues.

Fixes: [#3049](https://github.com/apache/logging-log4j2/issues/3049)

> [!IMPORTANT]  
> Base your changes on `2.x` branch if you are targeting Log4j 2; use `main` otherwise.

## Checklist

Before we can review and merge your changes, please go through the checklist below. If you're still working on some items, feel free to submit your pull request as a draft—our CI will help guide you through the remaining steps.

### ✅ Required checks

- [x] **License**: I confirm that my changes are submitted under the [Apache License, Version 2.0](https://apache.org/licenses/LICENSE-2.0).
- [x] **Commit signatures**: All commits are signed and verifiable. (See [GitHub Docs on Commit Signature Verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)).
- [x] **Code formatting**: The code is formatted according to the project’s style guide.
  <details>
    <summary>How to check and fix formatting</summary>

    - To **check** formatting: `./mvnw spotless:check`
    - To **fix** formatting: `./mvnw spotless:apply`

    See [the build instructions](https://logging.apache.org/log4j/2.x/development.html#building) for details.
  </details>
- [x] **Build & Test**: I verified that the project builds and all unit tests pass.
  <details>
    <summary>How to build the project</summary>

    Run: `./mvnw verify`

    See [the build instructions](https://logging.apache.org/log4j/2.x/development.html#building) for details.
  </details>

### 🧪 Tests (select one)

- [x] I have added or updated tests to cover my changes.
- [ ] No additional tests are needed for this change.

### 📝 Changelog (select one)

- [ ] I added a changelog entry in `src/changelog/.2.x.x`. (See [Changelog Entry File Guide](https://logging.apache.org/log4j/tools/log4j-changelog.html#changelog-entry-file)).
- [x] This is a trivial change and does not require a changelog entry.

### CODE REVIEW

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/async/AbstractAsyncThreadContextTestBase.java [hunk 1]
```diff
@@ -59,6 +60,11 @@ public abstract class AbstractAsyncThreadContextTestBase {
 
     private static TestProperties props;
 
+    @BeforeEach
+    public void beforeEach() {
+        ThreadContext.clearAll();
+    }
```
Comment (vy) [inline log4j-core-test/src/test/java/org/apache/logging/log4j/core/async/AbstractAsyncThreadContextTestBase.java:66]: We could consider repeating the same in an `@AfterAll` method too, but effective `log4j-core-test/pom.xml` states that `<reuseForks>false`. Hence, this is good enough for now.

**Review by vy — APPROVED** [review]

**Comment by vy** [comment]
@Kcruz28, thanks for the fix. Would you mind signing your commits, please? If you need guidance for that, [ChatGPT responds well](
https://chatgpt.com/share/689f0f3a-22b8-8002-90d7-6b7c1d702ffa) to the following prompt:

> In a GitHub PR, how can I sign (not sign-off!) existing commits?

**Comment by Kcruz28** [comment]
Hello, I believe I signed my commits. Please let me know if there are any issues.
