### PR TITLE
Fix `ArrayIndexOutOfBoundsException` in `ThrowableStackTraceRenderer` when the stack trace is mutated concurrently

### LINKED ISSUE #3940: ThrowableStackTraceRenderer can throw an ArrayIndexOutOfBoundsException when rendering a Throwable with a concurrently-mutated stacktrace
## Description

We observed this in Elasticsearch when attempting to upgrade to log4j 2.25.1.
In rare cases we drop stacktraces we don't care about on async response listeners prior to sending them over the wire. If these exceptions are also logged, we might hit an ArrayIndexOutOfBoundsException such as shown below.

## Configuration

**Version:** 2.25.1

**Operating system:** max OS, Linux 6.11.0-1017-gcp (amd64)

**JDK:** JDK 21, 24, 25

## Logs

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.apache.logging.log4j.core.pattern.ThrowableStackTraceRenderer.renderStackTraceElements(ThrowableStackTraceRenderer.java:169)
	at org.apache.logging.log4j.core.pattern.ThrowableStackTraceRenderer.renderThrowable(ThrowableStackTraceRenderer.java:110)
	at org.apache.logging.log4j.core.pattern.ThrowableStackTraceRenderer.renderThrowable(ThrowableStackTraceRenderer.java:87)
	at org.apache.logging.log4j.core.pattern.ThrowableStackTraceRenderer.renderThrowable(ThrowableStackTraceRenderer.java:59)
	at org.apache.logging.log4j.core.pattern.Main.lambda$main$0(Main.java:23)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:323)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:456)
```

## Reproduction

```java
package org.apache.logging.log4j.core.pattern;

import org.apache.logging.log4j.core.impl.ThrowableFormatOptions;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;

import static java.util.concurrent.TimeUnit.SECONDS;

public class Main {
    public static void main(String[] args) throws Exception {
        var stackTraceRenderer = ThrowableStackTraceRendererFactory.INSTANCE.createStackTraceRenderer(ThrowableFormatOptions.newInstance(null));
        var executor = Executors.newVirtualThreadPerTaskExecutor();

        for (int i = 0; i < 10; i++) {
            var latch = new CountDownLatch(2);
            var exception = new RuntimeException("exception");

            executor.submit(() -> {
                try {
                    stackTraceRenderer.renderThrowable(new StringBuilder(), exception, System.lineSeparator());
                    latch.countDown();
                } catch (Throwable e) {
                    e.printStackTrace();
                }
            });
            executor.submit(() -> {
                exception.setStackTrace(new StackTraceElement[0]);
                latch.countDown();
            });
            if (latch.await(10, SECONDS) == false) {
                throw new IllegalStateException("timed out waiting for tasks to complete");
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by mosche**
Fix `ArrayIndexOutOfBoundsException` in `ThrowableStackTraceRenderer` if concurrently modifying the stack trace of a `Throwable` while rendering it

Closes #3940

### CODE REVIEW

File: log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableStackTraceRenderer.java [hunk 1]
```diff
@@ -268,6 +267,11 @@ static final class Metadata {
              */
             final int stackLength;
 
+            /**
+             * The stack trace of this {@link Throwable}
```
Comment (vy) [inline log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableStackTraceRenderer.java]:
```suggestion
             * The stack trace of this {@link Throwable}.
             * This needs to be captured separately since {@link Throwable#getStackTrace()} can change.
             *
             * @see <a href="https://github.com/apache/logging-log4j2/issues/3940">#3940</a>
             * @see <a href="https://github.com/apache/logging-log4j2/pull/3955">#3955</a>
```

File: src/changelog/2.25.2/3940_ThrowableStackTraceRenderer_ArrayIndexOutOfBoundsException.xml [hunk 2]
```diff
@@ -0,0 +1,12 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<entry xmlns="https://logging.apache.org/xml/ns"
+       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+       xsi:schemaLocation="
+           https://logging.apache.org/xml/ns
+           https://logging.apache.org/xml/ns/log4j-changelog-0.xsd"
+       type="fixed">
+  <issue id="3940" link="https://github.com/apache/logging-log4j2/pull/3940"/>
+  <description format="asciidoc">
+    Fixes `ArrayIndexOutOfBoundsException` thrown by `ThrowableStackTraceRenderer` when a `Throwable`'s stacktrace is mutated concurrently.
```
Comment (vy) [inline src/changelog/2.25.2/3940_ThrowableStackTraceRenderer_ArrayIndexOutOfBoundsException.xml]:
```suggestion
  <issue id="3940" link="https://github.com/apache/logging-log4j2/issues/3940"/>
  <issue id="3955" link="https://github.com/apache/logging-log4j2/pull/3955"/>
  <description format="asciidoc">
    Fixes `ArrayIndexOutOfBoundsException` thrown by `ThrowableStackTraceRenderer` when the stack trace is mutated concurrently.
```

**Review by vy — APPROVED** [review]
@mosche, thanks so much for the contribution. I've confirmed that both tests (the new one, and the old one of #3929) fail in the absence their associated fixes.

**Comment by mosche** [comment]
Ugh, sorry, I missed configuring git to sign commits for this repo. My bad! Are you ok if I rewrite the history here? Sorry for that, you'll have to fix your commits afterwards then

**Comment by mosche** [comment]
Thanks for the quick response here btw!

**Comment by vy** [comment]
@mosche, yes, you must override the history. Please keep the content intact. `git rebase -i HEAD~6 && git push -f origin 3940_fix_ThrowableStackTraceRenderer` should do the trick. You can also squash all in one commit – but keep the diff intact.

**Review by vy — APPROVED** [review]
