### PR TITLE
Fix: prevent ThrowableStackTraceRenderer from throwing NPEs

### LINKED ISSUE #3929: ThrowableStackTraceRenderer throws NPE when rendering a Throwable with concurrently-mutated suppressions
## Description

The `ThrowableStackTraceRenderer` class can throw a `NullPointerException` if the suppressed exceptions associated with the `Throwable` it is rendering are being concurrently mutated. This is happening because `ThrowableStackTraceRenderer` invokes `Throwable#getSuppressed()` twice: once in `ThrowableStackTraceRenderer.Context.Metadata#populateMetadata()`, and a second time in `ThrowableStackTraceRenderer#renderThrowable()`, ahead of invoking `ThrowableStackTraceRenderer#renderSuppressed()`. If a racing thread manages to add a new suppressed exception to the being-logged exception between these two invocations, then the `Map<Throwable, Context.Metadata>` constructed by `populateMetadata()` will contain no mapping for the newly-added suppression, and as a result the dereference performed on line 168 explodes.

I have a repro below. To make the issue easier to detect, this repro does not use async logging, and I've configured the logger with `ignoreExceptions="false"` so that the NPE bubbles up to the logging site. However, it is worth noting that in an async logging setup, the appender responsible for invoking `ThrowableStackTraceRenderer` would run in the LMAX disruptor thread (rather than the application thread that submitted the log event), which likely means that this issue would occur if an application that uses async logging performed the following sequence of operations in a single thread:

1. Generate an exception, then
2. Log that exception, then
3. Perform an operation that resulted in the attachment of a new suppressed exception to the logged exception.

## Configuration

**Version:** 2.25.1

**Operating system:** mac OS

**JDK:** Java 21

## Logs

```
Log4jBugTest > test() STANDARD_ERROR
    2025-09-12T16:09:59.750535Z Test worker ERROR An exception occurred processing Appender CONSOLE
    java.lang.NullPointerException: Cannot read field "stackLength" because "metadata" is null
        at org.apache.logging.log4j.core.pattern.ThrowableStackTraceRenderer.renderStackTraceElements(ThrowableStackTraceRenderer.java:168)
        at org.apache.logging.log4j.core.pattern.ThrowableStackTraceRenderer.renderThrowable(ThrowableStackTraceRenderer.java:110)
        at org.apache.logging.log4j.core.pattern.ThrowableStackTraceRenderer.renderSuppressed(ThrowableStackTraceRenderer.java:133)
        at org.apache.logging.log4j.core.pattern.ThrowableStackTraceRenderer.renderThrowable(ThrowableStackTraceRenderer.java:111)
        at org.apache.logging.log4j.core.pattern.ThrowableStackTraceRenderer.renderThrowable(ThrowableStackTraceRenderer.java:87)
        at org.apache.logging.log4j.core.pattern.ThrowableStackTraceRenderer.renderThrowable(ThrowableStackTraceRenderer.java:59)
        at org.apache.logging.log4j.core.pattern.ThrowablePatternConverter.format(ThrowablePatternConverter.java:130)
        at org.apache.logging.log4j.core.layout.PatternLayout$NoFormatPatternSerializer.toSerializable(PatternLayout.java:354)
        at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:251)
        at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:237)
        at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:227)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:220)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:211)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:711)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:669)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:645)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:589)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:92)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:187)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2970)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2922)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2904)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2682)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2435)
        at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1779)
        at Log4jBugTest.test(Log4jBugTest.java:34)

```

## Reproduction

```
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicBoolean;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.Test;

public class Log4jBugTest {

    private static final Logger log = LogManager.getLogger(Log4jBugTest.class);

    @Test
    public void test() throws InterruptedException, ExecutionException {
        try (ExecutorService executor = Executors.newSingleThreadExecutor()) {
            for (int i = 0; i < 1000; i++) {
                AtomicBoolean done = new AtomicBoolean(false);
                CountDownLatch latch = new CountDownLatch(1);
                Exception e = new Exception("root-" + i);
                Future<?> f = executor.submit(() -> {
                    latch.countDown();
                    while (!done.get()) {
                        e.addSuppressed(new Exception("suppressed"));
                    }
                });
                latch.await();
                log.info("The error", e);
                done.set(true);
                f.get();
            }
        }
    }
}
```

And my log4j2 config:

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO">
    <Appenders>
        <Console name="CONSOLE" target="SYSTEM_OUT" ignoreExceptions="false">
            <PatternLayout pattern= "%d{dd MMM yyyy HH:mm:ss,SSS} [%p] (%t) %c: %m%n%ex"/>
        </Console>
    </Appenders>
    <Loggers>
        <Root level="INFO">
            <AppenderRef ref="CONSOLE" />
        </Root>
    </Loggers>
</Configuration>
```

### PR DESCRIPTION
**Pull request by joepembe**
The `ThrowableStackTraceRenderer` class can throw a `NullPointerException` if the suppressed exceptions associated with the `Throwable` it is rendering are being concurrently mutated. This happens because `ThrowableStackTraceRenderer` invokes `Throwable#getSuppressed()` twice: once in `ThrowableStackTraceRenderer.Context.Metadata#populateMetadata()`, and a second time in `ThrowableStackTraceRenderer#renderThrowable()`, ahead of invoking `ThrowableStackTraceRenderer#renderSuppressed()`. If a racing thread manages to add a new suppressed exception to the being-logged exception between these two invocations, then the `Map<Throwable, Context.Metadata>` constructed by `populateMetadata()` will contain no mapping for the newly-added suppression, and as a result the dereference performed on line 168 explodes.

Note: the unit test I am adding here requires the ability to mock `Throwable#getSuppressed()`. Since this method is `final`, I had to add a dependency on `mockito-inline`, which then required that I fix up some unrelated unit tests that had been relying on the lack of support for mocking `final` methods.

This fixes #3929

### CODE REVIEW

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/db/AbstractDatabaseAppenderTest.java
Comment (vy) [inline log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/db/AbstractDatabaseAppenderTest.java:1]: AFAICT these changes are unrelated. If so, would you mind reverting them, please? If so, would you mind explaining the rationale, please?

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/db/AbstractDatabaseManagerTest.java
Comment (vy) [inline log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/db/AbstractDatabaseManagerTest.java:1]: AFAICT these changes are unrelated. If so, would you mind reverting them, please? If so, would you mind explaining the rationale, please?

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RandomRollingAppenderOnStartupTest.java
Comment (vy) [inline log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RandomRollingAppenderOnStartupTest.java:1]: AFAICT these changes are unrelated. If so, would you mind reverting them, please? If so, would you mind explaining the rationale, please?

File: src/changelog/2.25.1/3929_ThrowableStackTraceRenderer-npe.xml [hunk 1]
```diff
@@ -0,0 +1,12 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<entry xmlns="https://logging.apache.org/xml/ns"
+       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+       xsi:schemaLocation="
+           https://logging.apache.org/xml/ns
+           https://logging.apache.org/xml/ns/log4j-changelog-0.xsd"
+       type="fixed">
+  <issue id="3929" link="https://github.com/apache/logging-log4j2/issues/3929"/>
```
Comment (vy) [inline src/changelog/2.25.1/3929_ThrowableStackTraceRenderer-npe.xml:8]:
```suggestion
  <issue id="3929" link="https://github.com/apache/logging-log4j2/issues/3929"/>
  <issue id="3934" link="https://github.com/apache/logging-log4j2/pull/3934"/>
```

File: log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableStackTraceRenderer.java [hunk 2]
```diff
@@ -268,9 +268,15 @@ static final class Metadata {
              */
             final int stackLength;
 
-            private Metadata(final int commonElementCount, final int stackLength) {
+            /**
+             * The suppressed exceptions attached to this {@link Throwable}
```
Comment (vy) [inline log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableStackTraceRenderer.java]:
```suggestion
             * The suppressed exceptions attached to this {@link Throwable}.
             * This needs to be captured separately since {@link Throwable#getSuppressed()} can change.
             * 
             * @see <a href="https://github.com/apache/logging-log4j2/issues/3929">#3929</a>
             * @see <a href="https://github.com/apache/logging-log4j2/pull/3934">#3934</a>
```

File: log4j-core-test/pom.xml [hunk 3]
```diff
@@ -347,6 +347,12 @@
       <scope>test</scope>
     </dependency>
 
+    <dependency>
+      <groupId>org.mockito</groupId>
+      <artifactId>mockito-inline</artifactId>
+      <scope>test</scope>
+    </dependency>
+
```
Comment (vy) [inline log4j-core-test/pom.xml]: Why do we need this?

**Review by vy — CHANGES_REQUESTED** [review]
Thanks so much for the contribution! Would you mind also extending following tests to reproduce the issue, please?

- `ExtendedThrowablePatternConverterTest`
- `RootThrowablePatternConverterTest`
- `ThrowablePatternConverterTest`

File: log4j-core-test/pom.xml (hunk 3 above)
Comment (joepembe) [reply log4j-core-test/pom.xml]: Oops! I wrote a unit test for these changes, but somehow it did not make it into the commit that I pushed to my forked repository. Apologies - I haven't used github much. I'll put together another revision and send it your way.

Anyways, the unit test that I wrote (and failed to include in the original PR) depends on the ability to specify mocked behavior for `Throwable#getSuppressed()`. Since `Throwable#getSuppressed()` is `final`, vanilla mockito can't do this - hence I added `mockito-inline`.

This is also the reason why I had to touch a handful of otherwise-unrelated tests beneath `log4j-core-test/`. These tests were silently depending on mockito's _inability_ to mock `final` methods, so they required some slight tweaking to get them to pass in the presence of `mockito-inline`.

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/db/AbstractDatabaseAppenderTest.java
Comment (joepembe) [reply log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/db/AbstractDatabaseAppenderTest.java:1]: See other comment.

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/db/AbstractDatabaseManagerTest.java
Comment (joepembe) [reply log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/db/AbstractDatabaseManagerTest.java:1]: See other comment.

File: log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RandomRollingAppenderOnStartupTest.java
Comment (joepembe) [reply log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RandomRollingAppenderOnStartupTest.java:1]: See other comment.

**Comment by joepembe** [comment]
> Thanks so much for the contribution! Would you mind also extending following tests to reproduce the issue, please?
> 
> * `ExtendedThrowablePatternConverterTest`
> * `RootThrowablePatternConverterTest`
> * `ThrowablePatternConverterTest`

Instead of modifying these tests, I added a new unit test specifically for `ThrowableStackTraceRenderer`. Is that sufficient?

File: log4j-core-test/pom.xml (hunk 3 above)
Comment (vy) [reply log4j-core-test/pom.xml]: I think we can test this anomaly without overriding `final` methods – see 0ba25694d, which also ensures this will be checked in all `{ExtendedThrowable,RootThrowable,Throwable}PatternConverterTest` classes.

**Review by vy — CHANGES_REQUESTED** [review]
Would you mind removing `ThrowableStackTraceRendererTest`, the newly `mockito-inline` dependency, and changes necessitated due to that, please?

File: log4j-core-test/pom.xml (hunk 3 above)
Comment (joepembe) [reply log4j-core-test/pom.xml]: This test takes an extremely long time to execute. I'm running it locally on my macbook pro, and I estimate that it will take 31 minutes to finish executing all 1,000,000 iterations of the `patternFormatter.format(logEvent, buffer);` loop. Are you sure this is the direction you want to go?

Comment (vy) [reply log4j-core-test/pom.xml]: You're right, it was an oversight from my side. Formatting should take place as long as there're active threads tampering the suppressed exception array. The following should do the trick:

```diff
Index: log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverterTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverterTest.java b/log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverterTest.java
--- a/log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverterTest.java	(revision 0ba25694d606f4ff483ae2b8717d5773b6f99dbc)
+++ b/log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverterTest.java	(date 1759507533630)
@@ -29,6 +29,7 @@
 import java.util.concurrent.CountDownLatch;
 import java.util.concurrent.ExecutorService;
 import java.util.concurrent.Executors;
+import java.util.concurrent.atomic.AtomicInteger;
 import java.util.concurrent.locks.LockSupport;
 import java.util.stream.Collectors;
 import java.util.stream.IntStream;
@@ -453,6 +454,7 @@
             final CountDownLatch startLatch =
                     new CountDownLatch(threadCount + /* the main thread invoking the rendering: */ 1);
             final int exceptionPerThreadCount = 100;
+            final AtomicInteger runningThreadCountRef = new AtomicInteger(threadCount);
 
             // Schedule threads that will start adding suppressed exceptions with the start signal
             for (int threadIndex = 0; threadIndex < threadCount; threadIndex++) {
@@ -472,6 +474,8 @@
                     } catch (InterruptedException ignored) {
                         // Restore the interrupt
                         Thread.currentThread().interrupt();
+                    } finally {
+                        runningThreadCountRef.decrementAndGet();
                     }
                 });
             }
@@ -491,7 +495,7 @@
             // Trigger the start latch and format the exception
             startLatch.countDown();
             startLatch.await();
-            for (int i = 0; i < 1_000_000; i++) {
+            while (runningThreadCountRef.get() > 0) {
                 // Give some time slack to increase randomness
                 LockSupport.parkNanos(1);
                 patternFormatter.format(logEvent, buffer);
```

Comment (joepembe) [reply log4j-core-test/pom.xml]: Done. Thanks!

**Review by vy — APPROVED** [review]
