### PR TITLE
Fix warning when last argument is null (#3975)

### LINKED ISSUE #3975: Logging with last implicit param a null Throwable generates framework warning
## Description

[Issue #2380](https://github.com/apache/logging-log4j2/issues/2380) introduces generation of framework warning when last (implicit) parameter is a null `Throwable`.

## Configuration

**Version:** 2.25.1

**Operating system:** Windows 11

**JDK:** Java HotSpot(TM) 64-Bit Server VM (build 25.461-b11, mixed mode)

## Logs

```
2025-10-30T13:17:14,249 ERROR [main] MyTest {} - Execution completed with result invalid
java.lang.RuntimeException: failed
	at ...

2025-10-30T11:17:14.252438500Z main WARN found 1 argument placeholders, but provided 2 for pattern `Execution completed with result {}`
2025-10-30T13:17:14,251 ERROR [main] MyTest  {} - Execution completed with result valid

```

## Reproduction
Some libraries provide execution results in an 'Either' style of structure (e.g. `dev.failsafe.event.ExecutionCompletedEvent`) --result or an exception. Such cases could conveniently be logged like
```
logger.error("Execution completed with result {}", outcome.result, outcome.failed);
```

That is, if we have failure `Throwable` -- log its stack trace. But if it is `null` and the error is described in `.result` -- just log what we have. This used to work properly until a fix for #2380 introduces a warning (WARN found 1 argument placeholders, but provided 2 for pattern), see sample test below and its output above.

```java
  record Result(
          String result,
          Throwable failed
  ) {}

  @Test
  void testLog4j() {
    var logger = org.apache.logging.log4j.LogManager.getLogger(MyTest.class);
    var failedResult = new Result("invalid", new RuntimeException("failed"));
    logger.error("Execution completed with result {}", failedResult.result, failedResult.failed);

    var validResult = new Result("valid", null);
    logger.error("Execution completed with result {}", validResult.result, validResult.failed);
  }
```

### PR DESCRIPTION
**Pull request by lrozenblyum**
Allow extra null argument to ParameterFormatter without issuing a warning.

Fixes #3975

### CODE REVIEW

File: log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java [hunk 1]
```diff
@@ -268,6 +267,12 @@ static void formatMessage(
         }
     }
 
+    private static boolean ignoreLastArgument(final Object[] args, final int argCount) {
```
Comment (ppkarwasz) [inline log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java]: _Nit_: naming is hard, but I think `isLastArgumentThrowable` would better reflect its purpose.

Alternatively the following logic could be refactored into a `getArgCountWithoutException` method:

```java
argCount < 1 ? 0 : argCount - (ignoreLastArgument(args, argCount) ? 1 : 0)
```

**Review by ppkarwasz — CHANGES_REQUESTED** [review]

File: log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java (hunk 1 above)
Comment (lrozenblyum) [reply log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterFormatter.java]: I've applied the first suggestion (`isLastArgumentThrowable`).

Extracting a method to get arg count - haven't done that because its naming itself is a big question :) Even the name `getArgCountWithoutLastThrowable` would be ambiguous. Technically it should sound `getArgCountIgnoringLastArgumentIfItIsThrowable` - yet it's too clumsy...

**Review by ppkarwasz — APPROVED** [review]
LGTM, thanks!

**Comment by lrozenblyum** [comment]
Thank you for fast review @ppkarwasz!
