### PR TITLE
Fix `Log4jFixedFormatter` buffer length

### LINKED ISSUE #1418: ArrayOutOfBoundsException in Log4jFixedFormatter
The current buffer used by `Log4jFixedFormatter` is too small for formats that contain a timezone specifier, since the size of the buffer is equal to the patterns length and a `Z` pattern produces 5 characters.

### PR DESCRIPTION
**Pull request by ppkarwasz**
This PR fixes #1418 .

The buffer length in `Log4jFixedFormatter` was computed base on the length of the pattern. Now it is the double of the real length of a formatted date (in the English locale).

At the same time this migrates the `FastDateFormatter` tests to JUnit 5.

### CODE REVIEW

File: log4j-core/src/main/java/org/apache/logging/log4j/core/util/datetime/FixedDateFormat.java [hunk 1]
```diff
@@ -255,7 +261,7 @@ private static int[] nanoRange(final String pattern) {
          * @return the length of the resulting formatted date and time strings
          */
         public int getLength() {
-            return pattern.length() - escapeCount;
+            return pattern.length() - escapeCount + extraTimeZoneFormatLength;
```
Comment (vy) [inline log4j-core/src/main/java/org/apache/logging/log4j/core/util/datetime/FixedDateFormat.java:264]: Given this is fixed, do we still need the `char[]`-size fix in `InstantFormatter`?

File: log4j-core/src/main/java/org/apache/logging/log4j/core/util/datetime/FixedDateFormat.java [hunk 2]
```diff
@@ -503,6 +510,15 @@ public String getFormat() {
         return fixedFormat.getPattern();
     }
 
+    /**
+     * Returns the length of the resulting formatted date and time strings.
+     *
+     * @return the length of the resulting formatted date and time strings
```
Comment (vy) [inline log4j-core/src/main/java/org/apache/logging/log4j/core/util/datetime/FixedDateFormat.java:516]: This description is not correct, otherwise we won't need to double the size of the buffer in `InstantFormatter`.

Comment (ppkarwasz) [reply log4j-core/src/main/java/org/apache/logging/log4j/core/util/datetime/FixedDateFormat.java:516]: Right, I should add "in the ROOT locale" (which is basically English, but less anglocentric).

Comment (vy) [reply log4j-core/src/main/java/org/apache/logging/log4j/core/util/datetime/FixedDateFormat.java:516]: I will appreciate that. Maybe also a note on _"if you want to determine the max. length, you better multiply this number by 2"_.
