### PR TITLE
Fix handling of `log4j2.messageFactory` and `log4j2.flowMessageFactory` properties

### LINKED ISSUE #2379: The `log4j2.messageFactory` property is ignored since 2.23.0
## Description

Due to the changes in version `2.23.0`, specifying an alternative default message factory through the `log4j2.messageFactory`
property does not work any more.

### PR DESCRIPTION
**Pull request by vy**
Fixes #2379.

### CODE REVIEW

File: log4j-core/src/main/java/org/apache/logging/log4j/core/Logger.java [hunk 1]
```diff
@@ -63,16 +77,82 @@ public class Logger extends AbstractLogger implements Supplier<LoggerConfig> {
...
+            } catch (final Throwable error) {
+                StatusLogger.getLogger()
+                        .error(
+                                "failed instantiating the `{}` class obtained from the `{}` property",
+                                className,
+                                propertyName,
+                                error);
+            }
+        }
+        return fallbackInstanceSupplier.get();
```
Comment (ppkarwasz) [inline log4j-core/src/main/java/org/apache/logging/log4j/core/Logger.java:155]: You could use `LoaderUtil#newCheckedInstanceOfProperty` here.

**Review by ppkarwasz — CHANGES_REQUESTED** [review]

File: log4j-core/src/main/java/org/apache/logging/log4j/core/Logger.java (hunk 1 above)
Comment (vy) [reply log4j-core/src/main/java/org/apache/logging/log4j/core/Logger.java]: Nice! Fixed in 097853933f8a19aa6333dd62d7fa5c06250452be.

**Review by ppkarwasz — APPROVED** [review]
